//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataFlow.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Core.EntityClient;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    
    
    public partial class NorthwindEntities : DbContext
    {
        public NorthwindEntities()
            : base("name=NorthwindEntities")
        {
        }
    
    	public override int SaveChanges()
    	{
    		var addedAuditedEntities = ChangeTracker.Entries<IAuditedEntity>()
    			.Where(p => p.State == EntityState.Added)
    			.Select(p => p.Entity);
    
    		string failReason = string.Empty;
    
    		var addedAuditedEntitieList = addedAuditedEntities.ToList();
    		for (int i = addedAuditedEntitieList.Count() - 1; i >= 0; i--)
    		{
    			var entity = addedAuditedEntitieList[i];
    			try
    			{
    				base.SaveChanges();
    			}
    			catch (DbUpdateException ex)
    			{
    				if (ex.InnerException != null && ex.InnerException.InnerException != null)
    				{
    					failReason += ex.InnerException.InnerException.Message + Environment.NewLine;
    				}
    				else
    				{
    					throw ex;
    				}
    			}
    			catch (System.Exception ex)
    			{
    				throw new Exception(ex.Message + failReason);
    			}
    		}
    
    		return 1;
    	}
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<CustomerDemographic> CustomerDemographics { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Order_Detail> Order_Details { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<Shipper> Shippers { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<Territory> Territories { get; set; }
    }
    
    public partial class EntityConnectionX
    {
    	public EntityConnection Connection { get; internal set; }
    
    	public EntityConnectionX()
    	{
    		EntityConnection connection = new EntityConnection("name=NorthwindEntities");
    
    		// Open the connection.
    		connection.Open();
    		this.Connection = connection;
    	}
    }
}
